# Site settings
title: D6
email: kkya2016@163.com
description: > # this means to ignore newlines until "baseurl:"
  369Cloud 致力于打造移动互联网云平台研发生态系统，将移动应用开发与移动应用云服务（BaaS、IaaS服务）完美集成，为开发者提供集成开发环境、移动应用开发引擎、基础服务、后端服务等一站式的移动应用开发解决方案；由369Cloud 自主研发的一体化开发流程，实现从应用创建、自定义认证、组件选择、模板配置、到混合平台编译等一系列可视化、可配置化操作，最大程度的为开发者及创业团队节约时间成本、人力成本、资金成本。

url: "http://369cloud.github.io/D6" # the base hostname & protocol for your site


# Dependencies
highlighter:  rouge

# Permalinks
permalink:    pretty

# Build settings
markdown: kramdown

baseurl: /D6

# Server
source:       docs
host:         127.0.0.1
port:         8080
